
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ptcl
 */
public class Train_info extends javax.swing.JFrame {

    /**
     * Creates new form Train_info
     */
    public Train_info() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ShowPrice = new javax.swing.JTextField();
        CBox = new javax.swing.JComboBox<>();
        Show = new javax.swing.JButton();
        CBox2 = new javax.swing.JComboBox<>();
        CBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Destination          :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Train Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Train             :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Source           :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Destination    :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Price               :");

        ShowPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPriceActionPerformed(evt);
            }
        });

        CBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karakoram", "Awam Express", "Allama Iqbal Express", "Green Line", "Karachi Express", "Khyber Mall" }));
        CBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxActionPerformed(evt);
            }
        });

        Show.setBackground(new java.awt.Color(255, 255, 255));
        Show.setText("Show");
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });

        CBox2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hyderabad Jn", "Tando Adam", "Nawabshah Jn", "Mahrabpur", "Rohri Jn", "Ghotki", "Sadikabad", "Rahim Yar Khan", "Khanpur Jn.", "Bahawalpur", "Dunyapur", "Jahania", "Khanewal Jn", "Chichawatni", "Sahiwa", "Okara", "Pattoki", "Kot Radha Kishen", "Raiwind Jn.", "Kot Lakhpat", "Lahore Jn." }));
        CBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox2ActionPerformed(evt);
            }
        });

        CBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karachi Cantt", "Hyderabad Jn", "Tando Adam", "Nawabshah Jn", "Mahrabpur", "Rohri Jn", "Ghotki", "Sadikabad", "Rahim Yar Khan", "Khanpur Jn.", "Bahawalpur", "Dunyapur", "Jahania", "Khanewal Jn", "Chichawatni", "Sahiwa", "Okara", "Pattoki", "Kot Radha Kishen", "Raiwind Jn.", "Kot Lakhpat", "Lahore Jn." }));
        CBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBox1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 184, Short.MAX_VALUE)
                            .addComponent(CBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 184, Short.MAX_VALUE)
                            .addComponent(ShowPrice, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_ShowMouseClicked

    private void CBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxActionPerformed

    private void CBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBox2ActionPerformed

    private void CBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBox1ActionPerformed

    private void ShowPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPriceActionPerformed
    
    }//GEN-LAST:event_ShowPriceActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        int Train=0,Ans,Num1 = 0,Num2 = 0;
        
        switch(CBox.getSelectedItem().toString()){
            case "Karakoram":
                Train+=850;
                break;
                
            case "Awam Express":
                Train+=950;
                break;
                
            case "Allama Iqbal Express":
                Train+=1050;
                break;
                
            case "Green Line":
                Train+=1100;
                break;
                
            case "Karachi Express":
                Train+=1150;
                break;
                
            case "Khyber Mall":
                Train+=1250;
                break;
        }
        
        switch(CBox2.getSelectedItem().toString()){
            case "Karachi Cantt":
                Num1 += 1;
                break;
                
            case "Hyderabad Jn":
                Num1 += 2;
                break;
                
            case "Tando Adam":
                Num1 += 3;
                break;
                
            case "Nawabshah Jn.":
                Num1 += 4;
                break;
                            
            case   "Mahrabpur":
                Num1 += 5;
                break;
                                  
            case "Rohri Jn.":
                Num1 += 6;
                break;
                
            case "Ghotki":
                Num1 += 7;
                break;
            case "Sadikabad":
                Num1 += 8;
                break;
                 
            case "Rahim Yar Khan":
                Num1 += 9;
                break;

            case "Khanpur Jn.":
                Num1 += 10;
                break;
                    
            case "Bahawalpur":
                Num1 += 11;
                break;

            case "Dunyapur":
                Num1 += 12;
                break;
            
            case "Jahania":
                Num1 += 13;
                break;

            case "Khanewal Jn":
                Num1 += 14;
                break;

            case "Chichawatni":
                Num1 += 15;
                break;

            case "Sahiwa":
                Num1 += 16;
                break;
                
            case "Okara":
                Num1 += 17;
                break;
                
            case "Pattoki":
                Num1 += 18;
                break;

            case "Kot Radha Kishen":
                Num1 += 19;
                break;
                
            case "Raiwind Jn.":
                Num1 += 20;
                break;
                
            case "Kot Lakhpat":
                Num1 += 21;
                break;
                
            case "Lahore Jn.":
                Num1 += 22;
                break;
                
        }
        
        switch(CBox1.getSelectedItem().toString()){
            case "Karachi Cantt":
                Num2 += 1;
                break;
                
            case "Hyderabad Jn":
                Num2 += 2;
                break;
                
            case "Tando Adam":
                Num2 += 3;
                break;
                
            case "Nawabshah Jn.":
                Num2 += 4;
                break;
                            
            case "Mahrabpur":
                Num2 += 5;
                break;
                                  
            case "Rohri Jn.":
                Num2 += 6;
                break;
                
            case "Ghotki":
                Num2 += 7;
                break;
            case "Sadikabad":
                Num2 += 8;
                break;
                 
            case "Rahim Yar Khan":
                Num2 += 9;
                break;

            case "Khanpur Jn.":
                Num2 += 10;
                break;
                    
            case "Bahawalpur":
                Num2 += 11;
                break;

            case "Dunyapur":
                Num2 += 12;
                break;
            
            case "Jahania":
                Num2 += 13;
                break;

            case "Khanewal Jn":
                Num2 += 14;
                break;

            case "Chichawatni":
                Num2 += 15;
                break;

            case "Sahiwa":
                Num2 += 16;
                break;
                
            case "Okara":
                Num2 += 17;
                break;
                
            case "Pattoki":
                Num2 += 18;
                break;

            case "Kot Radha Kishen":
                Num2 += 19;
                break;
                
            case "Raiwind Jn.":
                Num2 += 20;
                break;
                
            case "Kot Lakhpat":
                Num2 += 21;
                break;
                
            case "Lahore Jn.":
                Num2 += 22;
                break;
           
        }
        Ans = (Num1 - Num2)*Train;
        ShowPrice.setText(String.valueOf(Ans));
    }//GEN-LAST:event_ShowActionPerformed
    
    final void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Welcome w=new Welcome();
        w.setVisible(true);
        w.pack();
        w.setLocationRelativeTo(null);
        w.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Train_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Train_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Train_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Train_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Train_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBox;
    private javax.swing.JComboBox<String> CBox1;
    private javax.swing.JComboBox<String> CBox2;
    private javax.swing.JButton Show;
    private javax.swing.JTextField ShowPrice;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
